# Generated by Django 6.0 on 2025-12-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('WORK', 'Work'), ('OFF', 'Off'), ('LEAVE', 'Leave')], max_length=10)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracking.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('BREAK_START', 'Braek Start'), ('BREAK_END', 'Break End')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracking.employee')),
            ],
        ),
    ]
