# Generated by Django 6.0 on 2025-12-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0002_alter_schedule_time_end_alter_schedule_time_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='timeevent',
            name='event_type',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('BREAK_START', 'Break Start'), ('BREAK_END', 'Break End')], max_length=20),
        ),
    ]
