# Generated by Django 6.0 on 2025-12-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0003_alter_timeevent_options_alter_timeevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetracking.employee'),
        ),
        migrations.AlterField(
            model_name='timeevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
