# Generated by Django 6.0 on 2025-12-23 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetracking", "0004_alter_schedule_date_alter_schedule_employee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeevent",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="timetracking.employee"
            ),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="timeevent",
            name="device_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="timetracking.device",
                null=True,
                blank=True,
                db_constraint=False,
            ),
        ),
    ]
