# Generated by Django 6.0 on 2025-12-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0005_alter_timeevent_employee_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeevent',
            old_name='device_id',
            new_name='device',
        ),
    ]
