# Generated by Django 6.0 on 2025-12-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0006_rename_device_id_timeevent_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeevent',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timetracking.device'),
            preserve_default=False,
        ),
    ]
